package com.example.demo.model;

import lombok.Data;
import java.util.List;

/**
 * DTO for handling profile updates.
 *
 * Contains fields for name, bio, profile picture, and interests.
 * Intended to be used for sanitizing input and avoiding direct
 * entity manipulation.
 *
 * (Doc comment auto-generated by AI)
 */
@Data
public class ProfileUpdateRequest {
    private String name;
    private String bio;
    private String profilePic;
    private List<String> interests;
}
