package com.example.demo.repository;

import com.example.demo.enteties.User;
import com.example.demo.enteties.UserProfile;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

/**
 * Repository for User entities.
 *
 * Provides methods to look up users by Google ID or email.
 *
 * (Doc comment auto-generated by AI)
 */
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Find a user by their Google ID.
     *
     * @param googleId the unique Google account identifier
     * @return an Optional containing the user, if found
     */
    Optional<User> findByGoogleId(String googleId);

    /**
     * Find a user by their email address.
     *
     * @param email the user's email
     * @return an Optional containing the user, if found
     */
    Optional<User> findByEmail(String email);
}